#!/bin/bash

function scanIp () {

clear
  for ip in 192.168.1.{1..20}; do 
		ping -c 1 $ip  > /dev/null 2> /dev/null;
		if [ $? -eq 0 ]; then  	
			if [ ${1:-0 = nomac} ]; then
			printf '\e[1;31m%-6s\e[m' "+ ${ip} is up";
			printf "\n";
			else
			printf '\e[1;31m%-6s\e[m' "+ host: $ip  <== MAC: " & arp -n | grep $ip | awk '{print $3}' 
			fi
   		else
        		echo "- host ${ip} is down"
    			fi        
		done
}
scanIp $1;
